# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/dynamic_page.html
# Enabling this page by uncommenting the code below. It will result in a dynamic page but it will override the camera page!

dynamic_page:
  addon:
    name: Dashboard
    icon: mdi:monitor-dashboard
    path: 'dwains-theme/addons/dynamic_page/dashboard.yaml'
    data:
      some_data: 'This is some data parsed.'
      some_other_data: 'and some other data.'
