---
name: Home Assistant Check

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 22 * * *

jobs:
  yamllint:
    name: "Linting YAML"
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
  remarklint:
    name: "Linting Markdown"
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."
  home_assistant_stable:
    name: "Home Assistant - Stable"
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@master
      - name: Create secrets.yaml
        run: mv fake_secrets.yaml secrets.yaml
      - name: Delete Android TV
        run: rm packages/media/androidtv.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check Stable
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config . --script check_config --info all
  home_assistant_beta:
    name: "Home Assistant - Beta"
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@master
      - name: Create secrets.yaml
        run: mv fake_secrets.yaml secrets.yaml
      - name: Delete Android TV
        run: rm packages/media/androidtv.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check Latest
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: python -m homeassistant --config . --script check_config --info all
